import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'

const Layout = ({ children,pagina,guitarra }) => {
    return (
        <div>
            <Head>
                <title>Guitar LA - {pagina}</title>
                <meta name="description" content="Sitio web de ventas de Guitarras" />

                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700;900&display=swap" rel="stylesheet" />
            </Head>
            <Header guitarra={guitarra}/>
            <main className='alto'>
                {children}
            </main>
            <Footer />
        </div>

    )
}

Layout.defaultProps = {
    guitarra:null
}

export default Layout

/* <Head>
        <title>Guitar LA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='heading'>Holas</h1>
      <Link href='/nosotros'>desde nosotros</Link>*/